// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtNcGpRyKfMygl5gkRja_IboFI_u1qsSQ',
    appId: '1:525468154028:web:9a7d76a50189ceec2c0709',
    messagingSenderId: '525468154028',
    projectId: 'medhealth-b4fb0',
    authDomain: 'medhealth-b4fb0.firebaseapp.com',
    storageBucket: 'medhealth-b4fb0.appspot.com',
    measurementId: 'G-F6EGZ4JQMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD49t8rLzI6IXNLKlbxrSiosYd9DzRfFE',
    appId: '1:525468154028:android:723574db33de2fa32c0709',
    messagingSenderId: '525468154028',
    projectId: 'medhealth-b4fb0',
    storageBucket: 'medhealth-b4fb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOVT-p06XlHe3UT5AQWqeLD_d2U9uPC7o',
    appId: '1:525468154028:ios:19306601aef044082c0709',
    messagingSenderId: '525468154028',
    projectId: 'medhealth-b4fb0',
    storageBucket: 'medhealth-b4fb0.appspot.com',
    iosBundleId: 'com.example.medhealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOVT-p06XlHe3UT5AQWqeLD_d2U9uPC7o',
    appId: '1:525468154028:ios:19306601aef044082c0709',
    messagingSenderId: '525468154028',
    projectId: 'medhealth-b4fb0',
    storageBucket: 'medhealth-b4fb0.appspot.com',
    iosBundleId: 'com.example.medhealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtNcGpRyKfMygl5gkRja_IboFI_u1qsSQ',
    appId: '1:525468154028:web:7dd509f2d642932c2c0709',
    messagingSenderId: '525468154028',
    projectId: 'medhealth-b4fb0',
    authDomain: 'medhealth-b4fb0.firebaseapp.com',
    storageBucket: 'medhealth-b4fb0.appspot.com',
    measurementId: 'G-8TBCT11L41',
  );

}